### PR TITLE
fix : Issue 49 : Fix the typo injected by recent refactoring

### LINKED ISSUE #49: Bug when handling array data type response
When working on adding KRSNA to GenAI page came across a bug in Tarka Chat UI for handling array type response where [it is using](https://github.com/tarkalabs/tarka-chat/blob/c87f9c245c2c6138689b3d8d603a637cf0560e90/src/main.js#L268) an undefined `content` variable:

```
Uncaught (in promise) ReferenceError: content is not defined
    insertMessage tarka-chat-2.4.0.umd.js:23881
    insertMessage tarka-chat-2.4.0.umd.js:23880
    n tarka-chat-2.4.0.umd.js:23790
    render tarka-chat-2.4.0.umd.js:23818
    render tarka-chat-2.4.0.umd.js:23816
    init tarka-chat-2.4.0.umd.js:23705
    setupKrsna Krsna.js:8
    click Genai.vue:141
    VueJS 33
```

image

The returned response from `submitHandler` that threw above error was:
```json
[
  {
    "type": "text",
    "message": "A stunning 22k yellow gold bracelet with bead stations, perfect for weddings and cocktail events, crafted with 14K gold and weighing 4 grams."
  },
  {
    "type": "text",
    "message": "Elegant rose gold cross necklace with diamonds, perfect for religious women."
  },
  {
    "type": "text",
    "message": "Traditional Slightly Curved White Gold Ring for men, 1.5 grams, 22k, 77857 rupees. Classic design with a modern twist."
  }
]
```

### PR DESCRIPTION
**Pull request by su-docker**
This PR fixes #49

### CODE REVIEW

**Review by jahangiranwari — APPROVED** [review]

File: src/main.js [hunk 1]
```diff
@@ -265,7 +265,7 @@ export default {
 
     if (Array.isArray(data)) {
       data.forEach((d) => {
-        wrapper.appendChild(this.createNodeByType(content));
+        wrapper.appendChild(this.createNodeByType(data));
```
Comment (jahangiranwari) [inline src/main.js]: Shouldn't this be `d` instead of `data` ?

Comment (su-docker) [reply src/main.js]: Let me also write a sample data in the dev page

**Comment by su-docker** [comment]
@jahangiranwari Pushed a fix.

Screenshot 2024-04-15 at 10 04 16 PM

**Review by jahangiranwari — APPROVED** [review]
